In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("nba_games.csv", index_col=0)

In [3]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
1,240.0,240.0,36.0,100.0,0.360,7.0,31.0,0.226,16.0,19.0,...,50.0,32.6,152.0,111.0,ATL,98,0,2016,2015-12-09,False
2,240.0,240.0,37.0,85.0,0.435,8.0,19.0,0.421,17.0,23.0,...,20.0,30.9,148.0,116.0,SAS,107,1,2018,2017-10-18,False
3,240.0,240.0,41.0,89.0,0.461,8.0,21.0,0.381,17.0,19.0,...,28.6,30.9,138.0,118.0,MIN,99,0,2018,2017-10-18,True
4,240.0,240.0,27.0,86.0,0.314,6.0,26.0,0.231,15.0,20.0,...,16.8,30.9,157.0,90.0,MEM,92,1,2021,2021-04-30,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,34.2,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True
17768,240.0,240.0,37.0,74.0,0.500,13.0,25.0,0.520,26.0,37.0,...,25.0,30.0,139.0,129.0,ORL,108,1,2017,2016-12-14,True
17769,240.0,240.0,42.0,89.0,0.472,14.0,33.0,0.424,10.0,20.0,...,25.6,29.9,175.0,126.0,LAC,113,0,2017,2016-12-14,False
17770,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.7,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True
17771,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False

In [4]:
df = df.sort_values("date")

In [5]:
df = df.reset_index(drop=True)

In [6]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
1,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
2,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
3,240.0,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
4,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,...,42.9,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False
17768,240.0,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
17769,240.0,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
17770,240.0,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
17771,240.0,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [7]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [8]:
def add_target(group):
    group["target"] = group["won"].shift(-1)
    return group

df = df.groupby("team", group_keys=False).apply(add_target)

In [9]:
df[df["team"] == "PHI"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
28,240.0,34.0,83.0,0.410,7.0,22.0,0.318,20.0,23.0,0.870,...,42.9,239.0,107.0,BOS,112,1,2016,2015-10-28,False,False
52,240.0,19.0,63.0,0.302,6.0,15.0,0.400,27.0,37.0,0.730,...,33.1,200.0,94.0,UTA,99,0,2016,2015-10-30,False,False
92,240.0,38.0,85.0,0.447,7.0,24.0,0.292,17.0,23.0,0.739,...,34.2,171.0,112.0,CLE,107,0,2016,2015-11-02,False,False
130,240.0,34.0,81.0,0.420,6.0,28.0,0.214,13.0,15.0,0.867,...,42.0,110.0,105.0,MIL,91,1,2016,2015-11-04,False,False
157,240.0,41.0,79.0,0.519,10.0,23.0,0.435,10.0,15.0,0.667,...,31.9,177.0,113.0,CLE,108,1,2016,2015-11-06,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17697,240.0,38.0,84.0,0.452,8.0,30.0,0.267,19.0,22.0,0.864,...,33.4,200.0,114.0,MIA,119,1,2022,2022-05-04,False,True
17700,240.0,32.0,67.0,0.478,16.0,33.0,0.485,19.0,22.0,0.864,...,37.1,121.0,127.0,MIA,79,0,2022,2022-05-06,True,True
17711,240.0,37.0,68.0,0.544,16.0,33.0,0.485,26.0,34.0,0.765,...,28.6,155.0,129.0,MIA,108,0,2022,2022-05-08,True,False
17716,240.0,31.0,85.0,0.365,9.0,32.0,0.281,14.0,15.0,0.933,...,34.6,284.0,102.0,MIA,120,1,2022,2022-05-10,False,False
17727,240.0,36.0,87.0,0.414,12.0,37.0,0.324,6.0,7.0,0.857,...,36.5,152.0,107.0,MIA,99,0,2022,2022-05-12,False,NaN

In [10]:
df["target"][pd.isnull(df["target"])] = 2
df["target"] = df["target"].astype(int, errors="ignore")

<ipython-input-10-ac49a6f40115>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [11]:
df["won"].value_counts()

True     8886
False    8886
Name: won, dtype: int64

In [12]:
df["target"].value_counts()

1    8872
0    8870
2      30
Name: target, dtype: int64

In [13]:
nulls = pd.isnull(df).sum()

In [14]:
nulls = nulls[nulls > 0]

In [15]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [16]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [17]:
df = df[valid_columns].copy()

In [18]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False,0
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,2

In [21]:
from sklearn.linear_model import RidgeClassifier
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import TimeSeriesSplit

rr = RidgeClassifier(alpha=1)

split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, 
                                n_features_to_select=50, 
                                direction="forward",
                                cv=split,
                                n_jobs=1
                               )

In [22]:
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [23]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [24]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.277279,0.554502,0.317647,GSW,0.451923,1.0,2016,2015-10-27,False,0
1,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.160462,0.345972,0.317647,CHI,0.317308,1.0,2016,2015-10-27,False,1
2,0.0,0.409091,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.088575,0.232227,0.329412,CLE,0.298077,0.0,2016,2015-10-27,True,1
3,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.215661,0.530806,0.505882,NOP,0.298077,0.0,2016,2015-10-27,True,1
4,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.019255,0.203791,0.317647,DET,0.403846,0.0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.182285,0.208531,0.411765,GSW,0.413462,0.0,2022,2022-06-10,False,0
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.928113,1.000000,0.411765,BOS,0.288462,0.0,2022,2022-06-13,True,1
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.181001,0.630332,0.352941,GSW,0.384615,1.0,2022,2022-06-13,False,0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.120668,0.459716,0.400000,GSW,0.375000,0.0,2022,2022-06-16,False,2
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.263158,0.246445,0.576471,BOS,0.250000,1.0,2022,2022-06-16,True,2

In [25]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=50, n_jobs=1)

In [26]:
predictors = list(selected_columns[sfs.get_support()])

In [27]:
predictors

['mp',
 'fg%',
 '3p%',
 'ft',
 'fta',
 'ft%',
 'orb',
 'ts%',
 'ftr',
 'orb%',
 'trb%',
 'usg%',
 '3p%_max',
 'ft_max',
 'fta_max',
 'trb_max',
 '+/-_max',
 'drb%_max',
 'trb%_max',
 'tov%_max',
 'usg%_max',
 'home',
 'mp_opp',
 'fg_opp',
 '3p_opp',
 'ft%_opp',
 'blk_opp',
 'pf_opp',
 'drb%_opp',
 'trb%_opp',
 'blk%_opp',
 'usg%_opp',
 'fg_max_opp',
 'fga_max_opp',
 '3p_max_opp',
 '3p%_max_opp',
 'ft_max_opp',
 'ft%_max_opp',
 'trb_max_opp',
 'blk_max_opp',
 'tov_max_opp',
 'pf_max_opp',
 'pts_max_opp',
 '3par_max_opp',
 'drb%_max_opp',
 'ast%_max_opp',
 'stl%_max_opp',
 'blk%_max_opp',
 'usg%_max_opp',
 'home_opp']

In [28]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    
    seasons = sorted(data["season"].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        train = data[data["season"] < season]
        test = data[data["season"] == season]
        
        model.fit(train[predictors], train["target"])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [35]:
predictions = backtest(df, rr, predictors)

In [36]:
predictions

       actual  prediction
5250        1           1
5251        1           0
5252        0           0
5253        1           0
5254        0           0
...       ...         ...
17767       0           0
17768       1           1
17769       0           1
17770       2           1
17771       2           1

[12522 rows x 2 columns]

In [30]:
from sklearn.metrics import accuracy_score

accuracy_score(predictions["actual"], predictions["prediction"])

0.5430442421338444

In [31]:
df.groupby(["home"]).apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.428314
1.0    0.571686
dtype: float64

In [32]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.277279,0.554502,0.317647,GSW,0.451923,1.0,2016,2015-10-27,False,0
1,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.160462,0.345972,0.317647,CHI,0.317308,1.0,2016,2015-10-27,False,1
2,0.0,0.409091,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.088575,0.232227,0.329412,CLE,0.298077,0.0,2016,2015-10-27,True,1
3,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.215661,0.530806,0.505882,NOP,0.298077,0.0,2016,2015-10-27,True,1
4,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.019255,0.203791,0.317647,DET,0.403846,0.0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.182285,0.208531,0.411765,GSW,0.413462,0.0,2022,2022-06-10,False,0
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.928113,1.000000,0.411765,BOS,0.288462,0.0,2022,2022-06-13,True,1
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.181001,0.630332,0.352941,GSW,0.384615,1.0,2022,2022-06-13,False,0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.120668,0.459716,0.400000,GSW,0.375000,0.0,2022,2022-06-16,False,2
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.263158,0.246445,0.576471,BOS,0.250000,1.0,2022,2022-06-16,True,2

In [37]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

def find_team_averages(team):
    rolling = team.rolling(20).mean()
    return rolling

df_rolling = df_rolling.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

In [38]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,season
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.403409,0.325735,0.427392,0.487931,0.511364,0.439371,0.403488,0.347619,0.770012,...,0.04710,0.10400,0.457600,0.218806,0.421801,0.521765,0.355288,0.55,0.60,2022.0
17768,0.0,0.510227,0.383088,0.514354,0.470690,0.500000,0.440618,0.330233,0.300000,0.729930,...,0.06760,0.10310,0.399790,0.247176,0.577014,0.545294,0.419712,0.45,0.70,2022.0
17769,0.0,0.390909,0.319118,0.416986,0.486207,0.506061,0.441508,0.412791,0.361111,0.755309,...,0.04800,0.10100,0.440094,0.219448,0.419905,0.504706,0.355769,0.55,0.55,2022.0
17770,0.0,0.381818,0.312500,0.411364,0.481034,0.500758,0.441093,0.404651,0.353175,0.761085,...,0.04980,0.09840,0.405136,0.214313,0.426303,0.495882,0.351442,0.50,0.50,2022.0
17771,0.0,0.501136,0.388971,0.498206,0.474138,0.504545,0.439905,0.319767,0.287302,0.746966,...,0.06535,0.10725,0.434748,0.248780,0.570142,0.537647,0.412019,0.50,0.70,2022.0

In [39]:
rolling_cols = [f"{col}_20" for col in df_rolling.columns]
df_rolling.columns = rolling_cols
df = pd.concat([df, df_rolling], axis=1)

In [41]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_20,blk%_max_opp_20,tov%_max_opp_20,usg%_max_opp_20,ortg_max_opp_20,drtg_max_opp_20,total_opp_20,home_opp_20,won_20,season_20
0,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.409091,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.04710,0.10400,0.457600,0.218806,0.421801,0.521765,0.355288,0.55,0.60,2022.0
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.06760,0.10310,0.399790,0.247176,0.577014,0.545294,0.419712,0.45,0.70,2022.0
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.04800,0.10100,0.440094,0.219448,0.419905,0.504706,0.355769,0.55,0.55,2022.0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.04980,0.09840,0.405136,0.214313,0.426303,0.495882,0.351442,0.50,0.50,2022.0
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.06535,0.10725,0.434748,0.248780,0.570142,0.537647,0.412019,0.50,0.70,2022.0

In [42]:
df = df.dropna()

In [43]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_20,blk%_max_opp_20,tov%_max_opp_20,usg%_max_opp_20,ortg_max_opp_20,drtg_max_opp_20,total_opp_20,home_opp_20,won_20,season_20
506,0.0,0.454545,0.441176,0.392344,0.344828,0.363636,0.423990,0.395349,0.301587,0.883314,...,0.06265,0.08595,0.426572,0.144673,0.372986,0.447647,0.348558,0.50,0.60,2016.0
539,0.0,0.613636,0.411765,0.607656,0.551724,0.454545,0.559382,0.162791,0.158730,0.681447,...,0.07095,0.09120,0.405346,0.175995,0.360664,0.555294,0.345192,0.50,1.00,2016.0
546,0.0,0.318182,0.441176,0.234450,0.275862,0.348485,0.351544,0.255814,0.238095,0.708285,...,0.06440,0.08645,0.424371,0.149294,0.389100,0.445882,0.343750,0.50,0.60,2016.0
549,0.0,0.295455,0.382353,0.246411,0.310345,0.393939,0.356295,0.302326,0.365079,0.513419,...,0.06190,0.15825,0.500943,0.239024,0.433649,0.313529,0.365865,0.60,0.05,2016.0
552,0.0,0.250000,0.294118,0.253589,0.068966,0.181818,0.148456,0.465116,0.380952,0.813302,...,0.07215,0.11310,0.466090,0.149936,0.486967,0.401176,0.345192,0.50,0.55,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.04710,0.10400,0.457600,0.218806,0.421801,0.521765,0.355288,0.55,0.60,2022.0
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.06760,0.10310,0.399790,0.247176,0.577014,0.545294,0.419712,0.45,0.70,2022.0
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.04800,0.10100,0.440094,0.219448,0.419905,0.504706,0.355769,0.55,0.55,2022.0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.04980,0.09840,0.405136,0.214313,0.426303,0.495882,0.351442,0.50,0.50,2022.0
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.06535,0.10725,0.434748,0.248780,0.570142,0.537647,0.412019,0.50,0.70,2022.0

In [45]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

<ipython-input-45-f381b2951c98>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df, "home")
<ipython-input-45-f381b2951c98>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["team_opp_next"] = add_col(df, "team_opp")
<ipython-input-45-f381b2951c98>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df, "date")

In [46]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp_20,ortg_max_opp_20,drtg_max_opp_20,total_opp_20,home_opp_20,won_20,season_20,home_next,team_opp_next,date_next
506,0.0,0.454545,0.441176,0.392344,0.344828,0.363636,0.423990,0.395349,0.301587,0.883314,...,0.144673,0.372986,0.447647,0.348558,0.50,0.60,2016.0,1.0,TOR,2015-12-02
539,0.0,0.613636,0.411765,0.607656,0.551724,0.454545,0.559382,0.162791,0.158730,0.681447,...,0.175995,0.360664,0.555294,0.345192,0.50,1.00,2016.0,0.0,TOR,2015-12-05
546,0.0,0.318182,0.441176,0.234450,0.275862,0.348485,0.351544,0.255814,0.238095,0.708285,...,0.149294,0.389100,0.445882,0.343750,0.50,0.60,2016.0,1.0,LAL,2015-12-04
549,0.0,0.295455,0.382353,0.246411,0.310345,0.393939,0.356295,0.302326,0.365079,0.513419,...,0.239024,0.433649,0.313529,0.365865,0.60,0.05,2016.0,1.0,DEN,2015-12-05
552,0.0,0.250000,0.294118,0.253589,0.068966,0.181818,0.148456,0.465116,0.380952,0.813302,...,0.149936,0.486967,0.401176,0.345192,0.50,0.55,2016.0,1.0,PHO,2015-12-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.218806,0.421801,0.521765,0.355288,0.55,0.60,2022.0,0.0,GSW,2022-06-13
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.247176,0.577014,0.545294,0.419712,0.45,0.70,2022.0,0.0,BOS,2022-06-16
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.219448,0.419905,0.504706,0.355769,0.55,0.55,2022.0,1.0,GSW,2022-06-16
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.214313,0.426303,0.495882,0.351442,0.50,0.50,2022.0,NaN,NaN,NaN
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.248780,0.570142,0.537647,0.412019,0.50,0.70,2022.0,NaN,NaN,NaN

In [47]:
full = df.merge(df[rolling_cols + ["team_opp_next", "date_next", "team"]], left_on=["team", "date_next"], right_on=["team_opp_next", "date_next"])

In [49]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp_20_y,usg%_max_opp_20_y,ortg_max_opp_20_y,drtg_max_opp_20_y,total_opp_20_y,home_opp_20_y,won_20_y,season_20_y,team_opp_next_y,team_y
0,0.0,0.613636,0.411765,0.607656,0.551724,0.454545,0.559382,0.162791,0.158730,0.681447,...,0.387841,0.198460,0.345972,0.458235,0.311058,0.65,0.60,2016.0,GSW,TOR
1,0.0,0.295455,0.382353,0.246411,0.310345,0.393939,0.356295,0.302326,0.365079,0.513419,...,0.433281,0.143582,0.420853,0.403529,0.374519,0.55,0.35,2016.0,PHI,DEN
2,0.0,0.250000,0.294118,0.253589,0.068966,0.181818,0.148456,0.465116,0.380952,0.813302,...,0.387474,0.140116,0.492180,0.450588,0.403365,0.50,0.40,2016.0,MEM,PHO
3,0.0,0.431818,0.308824,0.478469,0.413793,0.348485,0.527316,0.395349,0.269841,1.000000,...,0.500943,0.239024,0.433649,0.313529,0.365865,0.60,0.05,2016.0,DEN,PHI
4,0.0,0.454545,0.470588,0.370813,0.275862,0.348485,0.351544,0.418605,0.333333,0.841307,...,0.405346,0.175995,0.360664,0.555294,0.345192,0.50,1.00,2016.0,TOR,GSW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13631,0.0,0.545455,0.426471,0.511962,0.448276,0.469697,0.440618,0.372093,0.365079,0.659277,...,0.425577,0.207060,0.568009,0.572353,0.430769,0.45,0.70,2022.0,BOS,GSW
13632,0.0,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.457600,0.218806,0.421801,0.521765,0.355288,0.55,0.60,2022.0,GSW,BOS
13633,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.428616,0.210270,0.577014,0.560000,0.425962,0.45,0.70,2022.0,BOS,GSW
13634,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.440094,0.219448,0.419905,0.504706,0.355769,0.55,0.55,2022.0,GSW,BOS
13635,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.399790,0.247176,0.577014,0.545294,0.419712,0.45,0.70,2022.0,BOS,GSW

In [50]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
0        GSW             TOR    TOR             GSW  2015-12-05
1        PHI             DEN    DEN             PHI  2015-12-05
2        MEM             PHO    PHO             MEM  2015-12-06
3        DEN             PHI    PHI             DEN  2015-12-05
4        TOR             GSW    GSW             TOR  2015-12-05
...      ...             ...    ...             ...         ...
13631    BOS             GSW    GSW             BOS  2022-06-10
13632    GSW             BOS    BOS             GSW  2022-06-13
13633    BOS             GSW    GSW             BOS  2022-06-13
13634    GSW             BOS    BOS             GSW  2022-06-16
13635    BOS             GSW    GSW             BOS  2022-06-16

[13636 rows x 5 columns]

In [51]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [52]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'team_opp_next_x',
 'date_next',
 'team_opp_next_y',
 'team_y',
 'season',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [53]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]
sfs.fit(full[selected_columns], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=50, n_jobs=1)

In [54]:
predictors = list(selected_columns[sfs.get_support()])

In [55]:
predictors

['fga',
 'orb',
 'tov%',
 'usg%',
 'fg%_max',
 'ft_max',
 'ft%_max',
 'drb_max',
 'ast_max',
 'stl%_max',
 'tov%_max',
 'drtg_max',
 'fta_opp',
 'blk%_opp',
 'usg%_opp',
 'ft%_max_opp',
 'tov_max_opp',
 'pts_max_opp',
 'drb%_max_opp',
 'ast%_max_opp',
 'stl%_max_opp',
 'pts_20_x',
 'usg%_20_x',
 'fga_max_20_x',
 'trb%_max_20_x',
 'total_20_x',
 'ast%_opp_20_x',
 'stl%_opp_20_x',
 'usg%_opp_20_x',
 'ft_max_opp_20_x',
 'ft%_max_opp_20_x',
 'stl_max_opp_20_x',
 'ftr_max_opp_20_x',
 'tov%_max_opp_20_x',
 'ortg_max_opp_20_x',
 'won_20_x',
 'home_next',
 'mp_20_y',
 'fga_20_y',
 'usg%_20_y',
 '+/-_max_20_y',
 'mp_opp_20_y',
 '3p%_opp_20_y',
 'blk_opp_20_y',
 'usg%_opp_20_y',
 'ast_max_opp_20_y',
 'stl_max_opp_20_y',
 'pts_max_opp_20_y',
 'ftr_max_opp_20_y',
 'blk%_max_opp_20_y']

In [56]:
predictions = backtest(full, rr, predictors)

In [57]:
accuracy_score(predictions["actual"], predictions["prediction"])

0.6448207379533815